// Generated by CoffeeScript 1.7.1
(function() {
  atom.workspaceView.eachEditorView(function(editorView) {
    var editor;
    editor = editorView.getEditor();
    console.log(editor);
    editor.setSoftTabs(true);
    return editor.setTabLength(4);
  });

}).call(this);
